# install_weekly_task.ps1 - Generate the scheduled-task registration script (write-only, never registers)
#
# This script generates scripts/register_weekly_task.ps1 containing the commands
# to register a Windows Scheduled Task. It does NOT execute the registration --
# review the generated file and run it yourself with elevated rights if desired.

$Root = Split-Path -Parent $PSScriptRoot
$CompileScript = Join-Path $Root "scripts/weekly_compile.ps1"
$OutFile = Join-Path $Root "scripts/register_weekly_task.ps1"

$Content = @"
# register_weekly_task.ps1 - generated by install_weekly_task.ps1
# Review this file, then run it with elevated rights to actually register the task.

`$Action = New-ScheduledTaskAction -Execute "powershell.exe" ``
    -Argument '-NoProfile -ExecutionPolicy Bypass -File "$CompileScript"' ``
    -WorkingDirectory "$Root"

# Runs every Friday at 19:00 local time
`$Trigger = New-ScheduledTaskTrigger -Weekly -DaysOfWeek Friday -At 19:00

# Catch up missed runs after wake, wake the machine to run, and allow running on battery
`$Settings = New-ScheduledTaskSettingsSet -StartWhenAvailable -WakeToRun -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries

Register-ScheduledTask -TaskName "llm-wiki-weekly-compile" ``
    -Action `$Action -Trigger `$Trigger -Settings `$Settings ``
    -Description "llm_wiki weekly compile: weekly_update + kimi editorial pass"
"@

Set-Content -Path $OutFile -Value $Content -Encoding UTF8
Write-Host "[done] registration script written to: $OutFile"
Write-Host "No scheduled task was registered. Review the generated script and run it manually if desired."
